name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      SHA: ${{ env.SHA }}
    steps:
    - name: Set short git commit SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
    - name: set variables
      uses: marcdomain/set-variables@v1.2
      with:
        variables: |
          SHA: "${{ env.SHA }}"
    
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ env.SHA }}
